### ISSUE TITLE
Move Applications to #applications

### ISSUE THREAD

**Issue by kkinziger** [badgerloop-software/website#28]
Can we move all new teammate apps from #teamleads to #applications

**Comment by vkottler** [comment]
Didn't require a code change FYI

**Comment by kkinziger** [comment]
tanks


Kali A. Kinziger
Communications | University of Wisconsin-Madison
Badgerloop President | www.badgerloop.com<http://www.badgerloop.com>
Academic Engagement Intern, CFYE | 155 Middleton Building
920.345.2548 | kkinziger@wisc.edu




________________________________
