### ISSUE TITLE
CSS Sucks instance #245209843572049385720345

### ISSUE THREAD

**Issue by kfish15** [badgerloop-software/website#56]
<img width="344" alt="screen shot 2017-10-07 at 11 28 03 pm" src="https://user-images.githubusercontent.com/24307914/31313924-4a382692-abb7-11e7-8864-86bdeb0d4be5.png">

Should the styling (edges) of these buttons be the same and should they be inline?

**Comment by kfish15** [comment]
https://giphy.com/gifs/reactionseditor-reaction-3o7bufkPz3LRof205G

**Comment by vkottler** [comment]
We don't style this button it was given to us
