### ISSUE TITLE
Fix my Lack of Angular Ability (Team.js)

### ISSUE THREAD

**Issue by kfish15** [badgerloop-software/website#6]
This is the current Angular setup I janked together to reference the data in team.js for the team popup (team-popup.html)

<img width="341" alt="screen shot 2017-06-25 at 11 48 42 pm" src="https://user-images.githubusercontent.com/24307914/27525144-ead46ca4-5a00-11e7-80a5-fb5f8156c089.png">

Its rough, I know. If you know a better way to reference all the data in that team.js in team-popup.html, such that when someone clicks on the team info button for a particular lead it pulls the data from team.js in their popup, then please make this more efficient. 

I think this can be done by setting the controller for the team-popup as the team.js file, but not sure.

**Comment by vkottler** [comment]
You want to just do `$scope.lead = lead` and then reference the individual object properties in the ui as `{{lead.name}}: {{lead.role}}` or however it actually is
